import React, { ReactNode } from 'react'
import HomeHeader from '../header'
import HomeFooter from '../footer'
import Head from 'next/head'
const MainHomeLayout: React.FC<{ children: ReactNode }> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex flex-col justify-between min-h-screen'>
                <HomeHeader></HomeHeader>
                <main className='flex-1'>{children}</main>
                <HomeFooter></HomeFooter>
            </div>
        </>
    )
}

export default MainHomeLayout